apiVersion: v1
kind: Service
metadata:
   name: notejam-app
   namespace: notejam-app
spec:
   selector:
       app: notejam-app
   ports:
     - protocol: TCP
       port: 3000
       targetPort: 3000 
